apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
        - name: container2
          image: us-east1-docker.pkg.dev/sylvan-presence-437615-e6/k8-assignment-artifact-registry/container2:latest
          volumeMounts:
            - mountPath: /malav_PV_dir
              name: standard-volume
      volumes:
        - name: standard-volume
          persistentVolumeClaim:
            claimName: standard-rwo-pvc